### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by achaussier**
Update  role style and structure

### CODE REVIEW

**Comment by conorsch** [comment]
Nice work. You should check out Molecule: https://github.com/metacloud/molecule/ It'll likely save you a lot of boilerplate when wiring up role tests via vagrant and testinfra.

**Comment by conorsch** [comment]
Any updates on merge here, @achaussier?

**Comment by achaussier** [comment]
Hi @conorsch ,

Sorry for the delay, I had many work on other projects.
I'll review all comments and changes this night.

**Comment by achaussier** [comment]
Some unexpected work occurred, but this night I'll take time to do this :/

**Comment by achaussier** [comment]
@conorsch I've took a look at the Molecule project some months ago, but it have change quickly, I'll take time to re-test it in the next days, and why not replace my current testing method.

Thanks

**Pull request merged**
